-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 21/05/2026 às 13:31
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `petmatch`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `animals`
--

CREATE TABLE `animals` (
  `id` varchar(50) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `species` varchar(100) DEFAULT NULL,
  `breed` varchar(100) DEFAULT NULL,
  `age` varchar(20) DEFAULT NULL,
  `sex` varchar(20) DEFAULT NULL,
  `size` varchar(20) DEFAULT NULL,
  `isFavorite` tinyint(1) DEFAULT NULL,
  `badges` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`badges`)),
  `environment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`environment`)),
  `behaviors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`behaviors`)),
  `compatibilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`compatibilities`)),
  `health` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`health`)),
  `description` text DEFAULT NULL,
  `story` text DEFAULT NULL,
  `images` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`images`)),
  `caretakerName` varchar(100) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `animals`
--

INSERT INTO `animals` (`id`, `name`, `category`, `species`, `breed`, `age`, `sex`, `size`, `isFavorite`, `badges`, `environment`, `behaviors`, `compatibilities`, `health`, `description`, `story`, `images`, `caretakerName`, `phone`, `email`) VALUES
('animal-001', 'Chico', 'Cão', 'Chihuahua', 'Chihuahua', '5 anos', 'Fêmea', 'Pequeno', 0, '[]', '[\"Casa com Quintal\",\"\\u00c1rea Rural\"]', '[\"Protetor\",\"Alegre\",\"Independente\"]', '[\"Soci\\u00e1vel com pessoas\",\"Sem Crian\\u00e7as\"]', '[\"Castrado\",\"Microchipado\",\"Vermifugado\"]', 'Chico é um animal de personalidade protetor e se adapta bem a ambientes casa com quintal.', 'Encontrado em uma feira, foi resgatado com saúde estável.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=1\"]', 'Patrícia Oliveira', '(11) 94943-4325', 'chico@petmatch.org'),
('animal-002', 'Loki', 'Cão', 'Dachshund', 'Dachshund', '4 anos', 'Macho', 'Médio', 0, '[]', '[\"S\\u00edtio\",\"\\u00c1rea Rural\"]', '[\"Quieto\",\"Brincalh\\u00e3o\",\"Independente\"]', '[\"Casa com Quintal\",\"Pode ficar sozinho\"]', '[\"Vermifugado\",\"Castrado\",\"Microchipado\"]', 'Loki é um animal de personalidade quieto e se adapta bem a ambientes sítio.', 'Encontrado em uma rua tranquila, foi resgatado com saúde estável.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=2\"]', 'Patrícia Oliveira', '(11) 93720-4665', 'loki@petmatch.org'),
('animal-003', 'Lola', 'Cão', 'SRD', 'SRD', '7 anos', 'Macho', 'Grande', 0, '[]', '[\"Casa Pequena\",\"\\u00c1rea Rural\"]', '[\"T\\u00edmido\",\"Curioso\",\"Carinhoso\"]', '[\"Pode ficar sozinho\",\"Bom com outros c\\u00e3es\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Lola é um animal de personalidade tímido e se adapta bem a ambientes casa pequena.', 'Encontrado em uma feira, foi resgatado com saúde estável.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=3\"]', 'Beatriz Rocha', '(11) 91524-5067', 'lola@petmatch.org'),
('animal-004', 'Dudu', 'Cão', 'Poodle', 'Poodle', '4 anos', 'Fêmea', 'Grande', 0, '[]', '[\"Casa Pequena\",\"Apartamento\"]', '[\"Calmo\",\"Ativo\",\"T\\u00edmido\"]', '[\"Casa com Quintal\",\"Ideal para Apartamento\"]', '[\"Castrado\",\"Vermifugado\",\"Microchipado\"]', 'Dudu é um animal de personalidade calmo e se adapta bem a ambientes casa pequena.', 'Encontrado em uma rua tranquila, foi resgatado com um pouco de medo.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=4\"]', 'Mariana Souza', '(11) 96279-1683', 'dudu@petmatch.org'),
('animal-005', 'Rex', 'Cão', 'Dachshund', 'Dachshund', '6 meses', 'Fêmea', 'Médio', 0, '[]', '[\"Casa Pequena\",\"Casa com Quintal\"]', '[\"Quieto\",\"Brincalh\\u00e3o\",\"Protetor\"]', '[\"N\\u00e3o gosta de gatos\",\"Casa com Quintal\"]', '[\"Microchipado\",\"Castrado\",\"Vacinado\"]', 'Rex é um animal de personalidade quieto e se adapta bem a ambientes casa pequena.', 'Encontrado em uma rua tranquila, foi resgatado com um ferimento leve.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=5\"]', 'Mariana Souza', '(11) 98382-7612', 'rex@petmatch.org'),
('animal-006', 'Marley', 'Cão', 'Beagle', 'Beagle', '5 anos', 'Fêmea', 'Pequeno', 0, '[]', '[\"Casa com Quintal\",\"Apartamento\"]', '[\"Curioso\",\"Ativo\",\"Brincalh\\u00e3o\"]', '[\"Aceita gatos\",\"Bom com Crian\\u00e7as\"]', '[\"Vermifugado\",\"Microchipado\",\"Castrado\"]', 'Marley é um animal de personalidade curioso e se adapta bem a ambientes casa com quintal.', 'Encontrado em um bosque, foi resgatado com muita energia.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=6\"]', 'Karen Lima', '(11) 93371-1480', 'marley@petmatch.org'),
('animal-007', 'Chico', 'Cão', 'Pastor Alemão', 'Pastor Alemão', '7 anos', 'Macho', 'Médio', 0, '\"SUPER MATCH\"', '[\"S\\u00edtio\",\"\\u00c1rea Rural\"]', '[\"Calmo\",\"Protetor\",\"Carinhoso\"]', '[\"Adora receber visitas\",\"Sem Crian\\u00e7as\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Chico é um animal de personalidade calmo e se adapta bem a ambientes sítio.', 'Encontrado em um bosque, foi resgatado com muita fome.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=7\"]', 'Mariana Souza', '(11) 91391-8900', 'chico@petmatch.org'),
('animal-008', 'Cacau', 'Cão', 'Bulldog', 'Bulldog', '6 meses', 'Fêmea', 'Pequeno', 0, '[]', '[\"\\u00c1rea Rural\",\"Apartamento\"]', '[\"Brincalh\\u00e3o\",\"Tranquilo\",\"Quieto\"]', '[\"Soci\\u00e1vel com pessoas\",\"Pode ficar sozinho\"]', '[\"Microchipado\",\"Castrado\",\"Vacinado\"]', 'Cacau é um animal de personalidade brincalhão e se adapta bem a ambientes área rural.', 'Encontrado em um bairro residencial, foi resgatado com um ferimento leve.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=8\"]', 'João Pedro', '(11) 96779-7295', 'cacau@petmatch.org'),
('animal-009', 'Lala', 'Cão', 'Chihuahua', 'Chihuahua', '8 anos', 'Fêmea', 'Pequeno', 0, '[]', '[\"Fazenda\",\"Apartamento\"]', '[\"Soci\\u00e1vel\",\"Independente\",\"Carinhoso\"]', '[\"Sem Crian\\u00e7as\",\"Aceita gatos\"]', '[\"Castrado\",\"Vacinado\",\"Microchipado\"]', 'Lala é um animal de personalidade sociável e se adapta bem a ambientes fazenda.', 'Encontrado em uma rua tranquila, foi resgatado com um ferimento leve.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=9\"]', 'Ana Clara', '(11) 97736-1712', 'lala@petmatch.org'),
('animal-010', 'Zeus', 'Cão', 'Pastor Alemão', 'Pastor Alemão', '1 ano', 'Fêmea', 'Grande', 0, '[]', '[\"\\u00c1rea Rural\",\"Casa Pequena\"]', '[\"Independente\",\"Tranquilo\",\"Quieto\"]', '[\"Pode ficar sozinho\",\"Aceita gatos\"]', '[\"Castrado\",\"Vermifugado\",\"Vacinado\"]', 'Zeus é um animal de personalidade independente e se adapta bem a ambientes área rural.', 'Encontrado em uma rua tranquila, foi resgatado com muita energia.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=10\"]', 'Patrícia Oliveira', '(11) 95917-3014', 'zeus@petmatch.org'),
('animal-011', 'Lili', 'Cão', 'Pastor Alemão', 'Pastor Alemão', '5 anos', 'Macho', 'Grande', 0, '[]', '[\"Casa Pequena\",\"Apartamento\"]', '[\"Calmo\",\"T\\u00edmido\",\"Soci\\u00e1vel\"]', '[\"Bom com Crian\\u00e7as\",\"Sem Crian\\u00e7as\"]', '[\"Castrado\",\"Microchipado\",\"Vermifugado\"]', 'Lili é um animal de personalidade calmo e se adapta bem a ambientes casa pequena.', 'Encontrado em uma feira, foi resgatado com um ferimento leve.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=11\"]', 'Bruno Alves', '(11) 99092-5617', 'lili@petmatch.org'),
('animal-012', 'Cacau', 'Cão', 'Labrador', 'Labrador', '3 anos', 'Macho', 'Grande', 0, '[]', '[\"Apartamento\",\"\\u00c1rea Rural\"]', '[\"Soci\\u00e1vel\",\"Tranquilo\",\"Calmo\"]', '[\"Bom com Crian\\u00e7as\",\"Adora receber visitas\"]', '[\"Castrado\",\"Vacinado\",\"Vermifugado\"]', 'Cacau é um animal de personalidade sociável e se adapta bem a ambientes apartamento.', 'Encontrado em um bairro residencial, foi resgatado com um pouco de medo.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=12\"]', 'Rafael Costa', '(11) 98982-7329', 'cacau@petmatch.org'),
('animal-013', 'Ginger', 'Cão', 'Golden Retriever', 'Golden Retriever', '8 anos', 'Macho', 'Grande', 0, '[]', '[\"\\u00c1rea Rural\",\"Apartamento\"]', '[\"Protetor\",\"Quieto\",\"Alegre\"]', '[\"Pode ficar sozinho\",\"N\\u00e3o gosta de gatos\"]', '[\"Vermifugado\",\"Castrado\",\"Microchipado\"]', 'Ginger é um animal de personalidade protetor e se adapta bem a ambientes área rural.', 'Encontrado em um bosque, foi resgatado com saúde estável.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=13\"]', 'Rafael Costa', '(11) 99689-3929', 'ginger@petmatch.org'),
('animal-014', 'Amora', 'Cão', 'Labrador', 'Labrador', '2 anos', 'Macho', 'Médio', 0, '\"SUPER MATCH\"', '[\"Casa Pequena\",\"Apartamento\"]', '[\"T\\u00edmido\",\"Quieto\",\"Tranquilo\"]', '[\"N\\u00e3o gosta de gatos\",\"Precisa de companhia\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Amora é um animal de personalidade tímido e se adapta bem a ambientes casa pequena.', 'Encontrado em uma feira, foi resgatado com muita energia.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=14\"]', 'Bruno Alves', '(11) 98190-1905', 'amora@petmatch.org'),
('animal-015', 'Teddy', 'Cão', 'Poodle', 'Poodle', '1 ano', 'Macho', 'Pequeno', 0, '[]', '[\"Casa com Quintal\",\"Casa Pequena\"]', '[\"T\\u00edmido\",\"Independente\",\"Carinhoso\"]', '[\"Bom com Crian\\u00e7as\",\"Pode ficar sozinho\"]', '[\"Castrado\",\"Vacinado\",\"Microchipado\"]', 'Teddy é um animal de personalidade tímido e se adapta bem a ambientes casa com quintal.', 'Encontrado em um bairro residencial, foi resgatado com um pouco de medo.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=15\"]', 'Gustavo Lima', '(11) 99282-6820', 'teddy@petmatch.org'),
('animal-016', 'Milo', 'Cão', 'Dachshund', 'Dachshund', '8 anos', 'Fêmea', 'Médio', 0, '[]', '[\"Fazenda\",\"Casa com Quintal\"]', '[\"Curioso\",\"Ativo\",\"Quieto\"]', '[\"Bom com Crian\\u00e7as\",\"Precisa de espa\\u00e7o\"]', '[\"Microchipado\",\"Castrado\",\"Vermifugado\"]', 'Milo é um animal de personalidade curioso e se adapta bem a ambientes fazenda.', 'Encontrado em um bosque, foi resgatado com um pouco de medo.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=16\"]', 'Ana Clara', '(11) 98137-6938', 'milo@petmatch.org'),
('animal-017', 'Bola', 'Cão', 'Poodle', 'Poodle', '6 meses', 'Macho', 'Grande', 0, '[]', '[\"Casa Pequena\",\"Fazenda\"]', '[\"Brincalh\\u00e3o\",\"Calmo\",\"Alegre\"]', '[\"Pode ficar sozinho\",\"Sem Crian\\u00e7as\"]', '[\"Vacinado\",\"Microchipado\",\"Castrado\"]', 'Bola é um animal de personalidade brincalhão e se adapta bem a ambientes casa pequena.', 'Encontrado em uma rua tranquila, foi resgatado com um pouco de medo.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=17\"]', 'Beatriz Rocha', '(11) 98773-8525', 'bola@petmatch.org'),
('animal-018', 'Mia', 'Cão', 'Pastor Alemão', 'Pastor Alemão', '4 anos', 'Macho', 'Médio', 0, '[]', '[\"Casa Pequena\",\"Casa com Quintal\"]', '[\"Quieto\",\"Ativo\",\"Alegre\"]', '[\"Pode ficar sozinho\",\"Adora receber visitas\"]', '[\"Castrado\",\"Microchipado\",\"Vacinado\"]', 'Mia é um animal de personalidade quieto e se adapta bem a ambientes casa pequena.', 'Encontrado em um parque, foi resgatado com muita fome.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=18\"]', 'Ana Clara', '(11) 98302-2953', 'mia@petmatch.org'),
('animal-019', 'Oliver', 'Cão', 'Shih Tzu', 'Shih Tzu', '2 anos', 'Fêmea', 'Médio', 0, '[]', '[\"Apartamento\",\"Casa Pequena\"]', '[\"Independente\",\"Soci\\u00e1vel\",\"Ativo\"]', '[\"Sem Crian\\u00e7as\",\"Pode ficar sozinho\"]', '[\"Vacinado\",\"Castrado\",\"Microchipado\"]', 'Oliver é um animal de personalidade independente e se adapta bem a ambientes apartamento.', 'Encontrado em um bosque, foi resgatado com muita energia.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=19\"]', 'Karen Lima', '(11) 93612-9286', 'oliver@petmatch.org'),
('animal-020', 'Max', 'Cão', 'Chihuahua', 'Chihuahua', '1 ano', 'Macho', 'Pequeno', 0, '[]', '[\"Casa com Quintal\",\"Casa Pequena\"]', '[\"Protetor\",\"Tranquilo\",\"T\\u00edmido\"]', '[\"Sem Crian\\u00e7as\",\"Ideal para Apartamento\"]', '[\"Castrado\",\"Microchipado\",\"Vermifugado\"]', 'Max é um animal de personalidade protetor e se adapta bem a ambientes casa com quintal.', 'Encontrado em um bosque, foi resgatado com saúde estável.', '[\"https:\\/\\/placedog.net\\/400\\/280?id=20\"]', 'Ana Clara', '(11) 98761-7035', 'max@petmatch.org'),
('animal-021', 'Dudu', 'Gato', 'SRD', 'SRD', '1 ano', 'Fêmea', 'Grande', 0, '\"SUPER MATCH\"', '[\"Apartamento\",\"Casa com Quintal\"]', '[\"Protetor\",\"Calmo\",\"Brincalh\\u00e3o\"]', '[\"Precisa de espa\\u00e7o\",\"Ideal para Apartamento\"]', '[\"Castrado\",\"Microchipado\",\"Vermifugado\"]', 'Dudu é um animal de personalidade protetor e se adapta bem a ambientes apartamento.', 'Encontrado em um parque, foi resgatado com muita fome.', '[\"https:\\/\\/labovet.com.br\\/wp-content\\/uploads\\/2022\\/09\\/2.png\"]', 'João Pedro', '(11) 93411-5110', 'dudu@petmatch.org'),
('animal-022', 'Tina', 'Gato', 'Siamês', 'Siamês', '3 anos', 'Macho', 'Grande', 0, '[]', '[\"Casa Pequena\",\"Apartamento\"]', '[\"Alegre\",\"Protetor\",\"Ativo\"]', '[\"Bom com Crian\\u00e7as\",\"Precisa de espa\\u00e7o\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Tina é um animal de personalidade alegre e se adapta bem a ambientes casa pequena.', 'Encontrado em uma feira, foi resgatado com saúde estável.', '[\"https:\\/\\/www.petz.com.br\\/blog\\/wp-content\\/uploads\\/2022\\/10\\/gato-siames-muda-de-cor.jpg\"]', 'João Pedro', '(11) 92758-1826', 'tina@petmatch.org'),
('animal-023', 'Simba', 'Gato', 'Persa', 'Persa', '1 ano', 'Fêmea', 'Médio', 0, '[]', '[\"Apartamento\",\"Fazenda\"]', '[\"Protetor\",\"Carinhoso\",\"Curioso\"]', '[\"Soci\\u00e1vel com pessoas\",\"Bom com Crian\\u00e7as\"]', '[\"Castrado\",\"Vacinado\",\"Vermifugado\"]', 'Simba é um animal de personalidade protetor e se adapta bem a ambientes apartamento.', 'Encontrado em um bairro residencial, foi resgatado com muita energia.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/e\\/e9\\/Male_Burmilla_cat.jpeg\\/120px-Male_Burmilla_cat.jpeg\"]', 'Patrícia Oliveira', '(11) 96885-7742', 'simba@petmatch.org'),
('animal-024', 'Zeca', 'Gato', 'Maine Coon', 'Maine Coon', '7 anos', 'Macho', 'Grande', 0, '[]', '[\"Casa Pequena\",\"Fazenda\"]', '[\"Calmo\",\"Quieto\",\"Independente\"]', '[\"Bom com Crian\\u00e7as\",\"Aceita gatos\"]', '[\"Vermifugado\",\"Castrado\",\"Microchipado\"]', 'Zeca é um animal de personalidade calmo e se adapta bem a ambientes casa pequena.', 'Encontrado em um bosque, foi resgatado com um ferimento leve.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/d\\/d0\\/Maine_Coon_female.jpg\\/120px-Maine_Coon_female.jpg\"]', 'Karen Lima', '(11) 92629-9929', 'zeca@petmatch.org'),
('animal-025', 'Bella', 'Gato', 'Siberiano', 'Siberiano', '4 anos', 'Macho', 'Grande', 0, '[]', '[\"Casa com Quintal\",\"Casa Pequena\"]', '[\"Alegre\",\"Soci\\u00e1vel\",\"T\\u00edmido\"]', '[\"Casa com Quintal\",\"Soci\\u00e1vel com pessoas\"]', '[\"Microchipado\",\"Castrado\",\"Vacinado\"]', 'Bella é um animal de personalidade alegre e se adapta bem a ambientes casa com quintal.', 'Encontrado em um bairro residencial, foi resgatado com muita energia.', '[\"https:\\/\\/www.patasdacasa.com.br\\/sites\\/default\\/files\\/2023-08\\/GettyImages-1432957013.jpg\"]', 'Rafael Costa', '(11) 94306-4957', 'bella@petmatch.org'),
('animal-026', 'Lia', 'Gato', 'Siberiano', 'Siberiano', '4 anos', 'Macho', 'Grande', 0, '[]', '[\"Fazenda\",\"Casa com Quintal\"]', '[\"Soci\\u00e1vel\",\"Quieto\",\"Tranquilo\"]', '[\"N\\u00e3o gosta de gatos\",\"Bom com outros c\\u00e3es\"]', '[\"Microchipado\",\"Vacinado\",\"Castrado\"]', 'Lia é um animal de personalidade sociável e se adapta bem a ambientes fazenda.', 'Encontrado em uma rua tranquila, foi resgatado com muita fome.', '[\"https:\\/\\/petcaramelo.com\\/wp-content\\/uploads\\/2021\\/02\\/Gato-Siberiano.jpg\"]', 'Bruno Alves', '(11) 97210-6680', 'lia@petmatch.org'),
('animal-027', 'Thor', 'Gato', 'Exótico', 'Exótico', '6 meses', 'Macho', 'Pequeno', 0, '[]', '[\"Casa Pequena\",\"\\u00c1rea Rural\"]', '[\"Calmo\",\"Independente\",\"Curioso\"]', '[\"Precisa de espa\\u00e7o\",\"Ideal para Apartamento\"]', '[\"Vacinado\",\"Castrado\",\"Vermifugado\"]', 'Thor é um animal de personalidade calmo e se adapta bem a ambientes casa pequena.', 'Encontrado em um bairro residencial, foi resgatado com muita energia.', '[\"https:\\/\\/www.zooplus.pt\\/magazine\\/wp-content\\/uploads\\/2022\\/07\\/exotico_3.webp\"]', 'Ana Clara', '(11) 97126-6159', 'thor@petmatch.org'),
('animal-028', 'Amora', 'Gato', 'Bengal', 'Bengal', '7 anos', 'Macho', 'Médio', 0, '\"SUPER MATCH\"', '[\"Fazenda\",\"Apartamento\"]', '[\"Tranquilo\",\"Ativo\",\"Quieto\"]', '[\"Pode ficar sozinho\",\"Aceita gatos\"]', '[\"Vermifugado\",\"Castrado\",\"Microchipado\"]', 'Amora é um animal de personalidade tranquilo e se adapta bem a ambientes fazenda.', 'Encontrado em uma feira, foi resgatado com muita fome.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/b\\/ba\\/Paintedcats_Red_Star_standing.jpg\\/120px-Paintedcats_Red_Star_standing.jpg\"]', 'Karen Lima', '(11) 98442-3085', 'amora@petmatch.org'),
('animal-029', 'Bento', 'Gato', 'Angorá', 'Angorá', '7 anos', 'Fêmea', 'Grande', 0, '[]', '[\"Apartamento\",\"\\u00c1rea Rural\"]', '[\"Protetor\",\"Tranquilo\",\"Curioso\"]', '[\"Pode ficar sozinho\",\"Bom com outros c\\u00e3es\"]', '[\"Microchipado\",\"Castrado\",\"Vacinado\"]', 'Bento é um animal de personalidade protetor e se adapta bem a ambientes apartamento.', 'Encontrado em uma feira, foi resgatado com muita fome.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/3\\/39\\/Fantine_de_l%27Empire_Ottoman.jpg\\/120px-Fantine_de_l%27Empire_Ottoman.jpg\"]', 'Lucas Silva', '(11) 93359-6336', 'bento@petmatch.org'),
('animal-030', 'Kiko', 'Gato', 'Persa', 'Persa', '4 anos', 'Macho', 'Médio', 0, '[]', '[\"\\u00c1rea Rural\",\"S\\u00edtio\"]', '[\"T\\u00edmido\",\"Tranquilo\",\"Ativo\"]', '[\"Precisa de espa\\u00e7o\",\"Precisa de companhia\"]', '[\"Vermifugado\",\"Castrado\",\"Vacinado\"]', 'Kiko é um animal de personalidade tímido e se adapta bem a ambientes área rural.', 'Encontrado em uma feira, foi resgatado com saúde estável.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/e\\/e9\\/Male_Burmilla_cat.jpeg\\/120px-Male_Burmilla_cat.jpeg\"]', 'Karen Lima', '(11) 99831-3332', 'kiko@petmatch.org'),
('animal-031', 'Thor', 'Gato', 'Exótico', 'Exótico', '4 anos', 'Fêmea', 'Grande', 0, '[]', '[\"Apartamento\",\"Casa com Quintal\"]', '[\"Protetor\",\"Alegre\",\"Carinhoso\"]', '[\"N\\u00e3o gosta de gatos\",\"Sem Crian\\u00e7as\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Thor é um animal de personalidade protetor e se adapta bem a ambientes apartamento.', 'Encontrado em uma rua tranquila, foi resgatado com muita fome.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/1\\/19\\/Nipsu-Nappulan_Non-Stop_Exotic_shorthair.JPG\"]', 'Rafael Costa', '(11) 94312-2146', 'thor@petmatch.org'),
('animal-032', 'Max', 'Gato', 'Siamês', 'Siamês', '1 ano', 'Macho', 'Grande', 0, '[]', '[\"S\\u00edtio\",\"Apartamento\"]', '[\"Calmo\",\"Carinhoso\",\"Curioso\"]', '[\"Precisa de companhia\",\"Pode ficar sozinho\"]', '[\"Vermifugado\",\"Microchipado\",\"Vacinado\"]', 'Max é um animal de personalidade calmo e se adapta bem a ambientes sítio.', 'Encontrado em um parque, foi resgatado com muita energia.', '[\"https:\\/\\/revistaoeste.com\\/oestegeral\\/wp-content\\/uploads\\/2025\\/05\\/gato-siames_1747871503415.jpg\"]', 'Mariana Souza', '(11) 93640-7513', 'max@petmatch.org'),
('animal-033', 'Lia', 'Gato', 'Bengal', 'Bengal', '4 anos', 'Fêmea', 'Médio', 0, '[]', '[\"\\u00c1rea Rural\",\"Apartamento\"]', '[\"Independente\",\"Tranquilo\",\"Soci\\u00e1vel\"]', '[\"Precisa de companhia\",\"Sem Crian\\u00e7as\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Lia é um animal de personalidade independente e se adapta bem a ambientes área rural.', 'Encontrado em um bosque, foi resgatado com saúde estável.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/b\\/ba\\/Paintedcats_Red_Star_standing.jpg\\/120px-Paintedcats_Red_Star_standing.jpg\"]', 'Mariana Souza', '(11) 99882-7777', 'lia@petmatch.org'),
('animal-034', 'Lola', 'Gato', 'Sphynx', 'Sphynx', '2 anos', 'Fêmea', 'Grande', 0, '[]', '[\"Apartamento\",\"Casa com Quintal\"]', '[\"Alegre\",\"Calmo\",\"Ativo\"]', '[\"Bom com Crian\\u00e7as\",\"Soci\\u00e1vel com pessoas\"]', '[\"Vermifugado\",\"Castrado\",\"Microchipado\"]', 'Lola é um animal de personalidade alegre e se adapta bem a ambientes apartamento.', 'Encontrado em um bosque, foi resgatado com um ferimento leve.', '[\"https:\\/\\/www.petlife.com.br\\/blog\\/assets\\/post\\/gato-sphynx-66290420d13f977736bc04c1\\/sphynx2.jpg\"]', 'Ana Clara', '(11) 91830-6149', 'lola@petmatch.org'),
('animal-035', 'Teddy', 'Gato', 'Angorá', 'Angorá', '5 anos', 'Fêmea', 'Pequeno', 0, '\"SUPER MATCH\"', '[\"S\\u00edtio\",\"Apartamento\"]', '[\"Protetor\",\"Soci\\u00e1vel\",\"T\\u00edmido\"]', '[\"Bom com Crian\\u00e7as\",\"N\\u00e3o gosta de gatos\"]', '[\"Vermifugado\",\"Microchipado\",\"Castrado\"]', 'Teddy é um animal de personalidade protetor e se adapta bem a ambientes sítio.', 'Encontrado em uma feira, foi resgatado com um ferimento leve.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/3\\/39\\/Fantine_de_l%27Empire_Ottoman.jpg\\/120px-Fantine_de_l%27Empire_Ottoman.jpg\"]', 'Rafael Costa', '(11) 93673-2216', 'teddy@petmatch.org'),
('animal-036', 'Luna', 'Gato', 'Siberiano', 'Siberiano', '5 anos', 'Fêmea', 'Grande', 0, '[]', '[\"\\u00c1rea Rural\",\"S\\u00edtio\"]', '[\"Ativo\",\"Protetor\",\"Curioso\"]', '[\"Ideal para Apartamento\",\"Adora receber visitas\"]', '[\"Castrado\",\"Microchipado\",\"Vermifugado\"]', 'Luna é um animal de personalidade ativo e se adapta bem a ambientes área rural.', 'Encontrado em uma feira, foi resgatado com um ferimento leve.', '[\"https:\\/\\/siberiancatbreederscentral.com\\/wp-content\\/uploads\\/2016\\/08\\/Cher07.jpg\"]', 'Karen Lima', '(11) 95708-4427', 'luna@petmatch.org'),
('animal-037', 'Tina', 'Gato', 'Siberiano', 'Siberiano', '6 meses', 'Macho', 'Médio', 0, '[]', '[\"Fazenda\",\"Casa com Quintal\"]', '[\"Protetor\",\"Quieto\",\"Soci\\u00e1vel\"]', '[\"Adora receber visitas\",\"Ideal para Apartamento\"]', '[\"Vacinado\",\"Microchipado\",\"Castrado\"]', 'Tina é um animal de personalidade protetor e se adapta bem a ambientes fazenda.', 'Encontrado em um bosque, foi resgatado com saúde estável.', '[\"https:\\/\\/i0.wp.com\\/segredosdomundo.r7.com\\/wp-content\\/uploads\\/2020\\/02\\/gato-siberiano-caracteristicas-e-cuidados-basicos-para-a-raca.png?resize=640%2C400&quality=80&ssl=1\"]', 'Lucas Silva', '(11) 97974-2731', 'tina@petmatch.org'),
('animal-038', 'Simba', 'Gato', 'Ragdoll', 'Ragdoll', '1 ano', 'Fêmea', 'Grande', 0, '[]', '[\"Apartamento\",\"Casa com Quintal\"]', '[\"Carinhoso\",\"T\\u00edmido\",\"Ativo\"]', '[\"Precisa de companhia\",\"Ideal para Apartamento\"]', '[\"Microchipado\",\"Castrado\",\"Vacinado\"]', 'Simba é um animal de personalidade carinhoso e se adapta bem a ambientes apartamento.', 'Encontrado em uma área rural, foi resgatado com um pouco de medo.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/c\\/c3\\/Ragdoll.jpg\\/120px-Ragdoll.jpg\"]', 'Bruno Alves', '(11) 91089-4578', 'simba@petmatch.org'),
('animal-039', 'Ginger', 'Gato', 'Persa', 'Persa', '7 anos', 'Macho', 'Pequeno', 0, '[]', '[\"S\\u00edtio\",\"Apartamento\"]', '[\"Independente\",\"Soci\\u00e1vel\",\"Carinhoso\"]', '[\"Ideal para Apartamento\",\"Casa com Quintal\"]', '[\"Microchipado\",\"Vermifugado\",\"Vacinado\"]', 'Ginger é um animal de personalidade independente e se adapta bem a ambientes sítio.', 'Encontrado em um parque, foi resgatado com un ferimento leve.', '[\"https:\\/\\/upload.wikimedia.org\\/wikipedia\\/commons\\/thumb\\/e\\/e9\\/Male_Burmilla_cat.jpeg\\/120px-Male_Burmilla_cat.jpeg\"]', 'Ana Clara', '(11) 97936-8852', 'ginger@petmatch.org'),
('animal-040', 'Koda', 'Gato', 'Siamês', 'Siamês', '5 anos', 'Fêmea', 'Grande', 0, '[]', '[\"Fazenda\",\"\\u00c1rea Rural\"]', '[\"Carinhoso\",\"Calmo\",\"Independente\"]', '[\"Sem Crian\\u00e7as\",\"Adora receber visitas\"]', '[\"Castrado\",\"Vermifugado\",\"Vacinado\"]', 'Koda é um animal de personalidade carinhoso e se adapta bem a ambientes fazenda.', 'Encontrado em uma rua tranquila, foi resgatado com muita energia.', '[\"https:\\/\\/blog-static.petlove.com.br\\/wp-content\\/uploads\\/2021\\/08\\/Gato-siames.jpg\"]', 'Rafael Costa', '(11) 92124-4890', 'koda@petmatch.org'),
('animal-041', 'Amora', 'Silvestre', 'Tucano', 'Tucano', '8 anos', 'Macho', 'Médio', 0, '[]', '[\"\\u00c1rea Rural\",\"Fazenda\"]', '[\"Protetor\",\"Curioso\",\"Ativo\"]', '[\"Pode ficar sozinho\",\"Soci\\u00e1vel com pessoas\"]', '[\"Vermifugado\",\"Castrado\",\"Vacinado\"]', 'Amora é um animal de personalidade protetor e se adapta bem a ambientes área rural.', 'Encontrado em uma feira, foi resgatado com muita energia.', '[\"https:\\/\\/encrypted-tbn0.gstatic.com\\/images?q=tbn:ANd9GcQtwmQdbitnYo9MWWmyw4yS2Pur22qtsVdMCw&s\"]', 'Karen Lima', '(11) 98216-4580', 'amora@petmatch.org'),
('animal-042', 'Chico', 'Silvestre', 'Curiango', 'Curiango', '5 anos', 'Macho', 'Grande', 0, '\"SUPER MATCH\"', '[\"S\\u00edtio\",\"Apartamento\"]', '[\"Quieto\",\"Brincalh\\u00e3o\",\"Soci\\u00e1vel\"]', '[\"Bom com Crian\\u00e7as\",\"Pode ficar sozinho\"]', '[\"Vacinado\",\"Vermifugado\",\"Microchipado\"]', 'Chico é um animal de personalidade quieto e se adapta bem a ambientes sítio.', 'Encontrado em uma feira, foi resgatado with um pouco de medo.', '[\"https:\\/\\/s3.amazonaws.com\\/media.wikiaves.com.br\\/images\\/489\\/984231_2f56e264101a173e9bf9e52ea76dd4e3.jpg\"]', 'Patrícia Oliveira', '(11) 94708-8889', 'chico@petmatch.org'),
('animal-043', 'Marley', 'Silvestre', 'Porquinho-da-índia', 'Porquinho-da-índia', '4 anos', 'Fêmea', 'Grande', 0, '[]', '[\"Casa com Quintal\",\"Casa Pequena\"]', '[\"Ativo\",\"Curioso\",\"Independente\"]', '[\"Ideal para Apartamento\",\"Adora receber visitas\"]', '[\"Vermifugado\",\"Vacinado\",\"Microchipado\"]', 'Marley é um animal de personalidade ativo e se adapta bem a ambientes casa com quintal.', 'Encontrado em uma área rural, foi resgatado com um ferimento leve.', '[\"https:\\/\\/www.petz.com.br\\/blog\\/wp-content\\/uploads\\/2023\\/05\\/porquinho-da-india-peruano.jpg\"]', 'Gustavo Lima', '(11) 94141-2675', 'marley@petmatch.org'),
('animal-044', 'Teddy', 'Silvestre', 'Porquinho-da-índia', 'Porquinho-da-índia', '2 anos', 'Macho', 'Pequeno', 0, '[]', '[\"Casa Pequena\",\"\\u00c1rea Rural\"]', '[\"Independente\",\"Ativo\",\"Carinhoso\"]', '[\"Precisa de espa\\u00e7o\",\"Casa com Quintal\"]', '[\"Vermifugado\",\"Microchipado\",\"Castrado\"]', 'Teddy é um animal de personalidade independente e se adapta bem a ambientes casa pequena.', 'Encontrado em um parque, foi resgatado com um pouco de medo.', '[\"https:\\/\\/cdn0.peritoanimal.com.br\\/pt\\/posts\\/5\\/6\\/2\\/frutas_e_verduras_boas_para_os_porquinhos_da_india_20265_600.jpg\"]', 'Gustavo Lima', '(11) 94695-2794', 'teddy@petmatch.org'),
('animal-045', 'Loki', 'Silvestre', 'Tucano', 'Tucano', '1 ano', 'Macho', 'Grande', 0, '[]', '[\"S\\u00edtio\",\"Casa Pequena\"]', '[\"Protetor\",\"Quieto\",\"Calmo\"]', '[\"N\\u00e3o gosta de gatos\",\"Sem Crian\\u00e7as\"]', '[\"Vermifugado\",\"Vacinado\",\"Microchipado\"]', 'Loki é um animal de personalidade protetor e se adapta bem a ambientes sítio.', 'Encontrado em um bairro residencial, foi resgatado com um ferimento leve.', '[\"https:\\/\\/encrypted-tbn0.gstatic.com\\/images?q=tbn:ANd9GcQtwmQdbitnYo9MWWmyw4yS2Pur22qtsVdMCw&s\"]', 'Patrícia Oliveira', '(11) 99602-7452', 'loki@petmatch.org'),
('animal-046', 'Tobby', 'Silvestre', 'Furão', 'Furão', '7 anos', 'Macho', 'Pequeno', 0, '[]', '[\"Apartamento\",\"\\u00c1rea Rural\"]', '[\"Calmo\",\"Tranquilo\",\"T\\u00edmido\"]', '[\"Precisa de espa\\u00e7o\",\"Soci\\u00e1vel com pessoas\"]', '[\"Vacinado\",\"Microchipado\",\"Castrado\"]', 'Tobby é um animal de personalidade calmo e se adapta bem a ambientes apartamento.', 'Encontrado em um bairro residencial, foi resgatado com um pouco de medo.', '[\"https:\\/\\/encrypted-tbn0.gstatic.com\\/images?q=tbn:ANd9GcQnHwvg1NBi4h3ByS1Z3u1X1LMOfoO4k70aKQ&s\"]', 'João Pedro', '(11) 95469-6587', 'tobby@petmatch.org'),
('animal-047', 'Tobby', 'Silvestre', 'Iguana', 'Iguana', '1 ano', 'Fêmea', 'Médio', 0, '[]', '[\"Casa com Quintal\",\"Casa Pequena\"]', '[\"Calmo\",\"Tranquilo\",\"Soci\\u00e1vel\"]', '[\"Precisa de espa\\u00e7o\",\"Pode ficar sozinho\"]', '[\"Castrado\",\"Microchipado\",\"Vacinado\"]', 'Tobby é um animal de personalidade calmo e se adapta bem a ambientes casa com quintal.', 'Encontrado em um bairro residencial, foi resgatado com um pouco de medo.', '[\"https:\\/\\/paramais.com.br\\/wp-content\\/uploads\\/2025\\/05\\/4-fatos-sobre-a-iguana-verde-que-provam-sua-inteligencia.webp\"]', 'Patrícia Oliveira', '(11) 92042-6488', 'tobby@petmatch.org'),
('animal-048', 'Max', 'Silvestre', 'Papagaio', 'Papagaio', '5 anos', 'Fêmea', 'Médio', 0, '[]', '[\"Apartamento\",\"\\u00c1rea Rural\"]', '[\"Alegre\",\"Brincalh\\u00e3o\",\"Soci\\u00e1vel\"]', '[\"Sem Crian\\u00e7as\",\"Casa com Quintal\"]', '[\"Microchipado\",\"Vacinado\",\"Vermifugado\"]', 'Max é um animal de personalidade alegre e se adapta bem a ambientes apartamento.', 'Encontrado em um bairro residencial, foi resgatado com muita fome.', '[\"https:\\/\\/cobasiblog.blob.core.windows.net\\/production-ofc\\/2020\\/12\\/vive-um-papagaio-principal.png\"]', 'Karen Lima', '(11) 91409-3529', 'max@petmatch.org'),
('animal-049', 'Koda', 'Silvestre', 'Tucano', 'Tucano', '4 anos', 'Macho', 'Médio', 0, '\"SUPER MATCH\"', '[\"Fazenda\",\"S\\u00edtio\"]', '[\"Curioso\",\"Brincalh\\u00e3o\",\"T\\u00edmido\"]', '[\"N\\u00e3o gosta de gatos\",\"Casa com Quintal\"]', '[\"Vermifugado\",\"Castrado\",\"Vacinado\"]', 'Koda é um animal de personalidade curioso e se adapta bem a ambientes fazenda.', 'Encontrado em um parque, foi resgatado com um ferimento leve.', '[\"https:\\/\\/s2.glbimg.com\\/shVyfsOkEsvzsdRQWbutCuMJrxs=\\/400x350\\/top\\/e.glbimg.com\\/og\\/ed\\/f\\/original\\/2013\\/12\\/03\\/como_criar_tucano.jpg\"]', 'Ana Clara', '(11) 98648-4001', 'koda@petmatch.org'),
('animal-050', 'Teddy', 'Silvestre', 'Furão', 'Furão', '2 anos', 'Macho', 'Pequeno', 0, '[]', '[\"Apartamento\",\"Casa com Quintal\"]', '[\"Ativo\",\"Carinhoso\",\"Protetor\"]', '[\"Aceita gatos\",\"Casa com Quintal\"]', '[\"Castrado\",\"Vacinado\",\"Vermifugado\"]', 'Teddy é um animal de personalidade ativo e se adapta bem a ambientes apartamento.', 'Encontrado em um bosque, foi resgatado com muita fome.', '[\"https:\\/\\/clinicapetmarket.com.br\\/wp-content\\/uploads\\/2021\\/05\\/capa-blog.png\"]', 'Gustavo Lima', '(11) 97210-9903', 'teddy@petmatch.org');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `animals`
--
ALTER TABLE `animals`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
